version: '3'
services: 
  dev:
    image: ${DOCKER_IMAGE_DEV:-node:8.1.3-alpine}
    working_dir: /opt/app
    command: sh run-dev.sh
    environment: 
      NODE_ENV: development
      PORT: 8080
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: unsplash.dev
      HTTPS_METHOD: noredirect
    ports: 
      - "8080"
    volumes: 
      - .:/opt/app
    restart: unless-stopped
    network_mode: bridge
