version: '3'
services: 
  dev:
    image: node:8.4-alpine
    working_dir: /opt/app
    command: sh run-dev.sh
    environment: 
      NODE_ENV: development
      PORT: 8080
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: unsplash.dev
      HTTPS_METHOD: noredirect
    ports: 
      - "8080"
      - "6006" #port for storybook
    volumes: 
      - .:/opt/app
    restart: unless-stopped
    network_mode: bridge
